//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTaskInfocom
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> EquipmentId { get; set; }
        public string Description { get; set; }
        public byte[] Base64 { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
